{% set name = "wdmtoolbox" %}
{% set version = "16.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wdmtoolbox-{{ version }}.tar.gz
  sha256: 808e0660643b73cafcee2245f3ef08408e50e954559084a9ddbdca24dedb4c84

build:
  script_env:
    - FC_LD=ld  # [win]
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - meson-python
    - meson
  host:
    - meson-python
    - meson
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - numpy
    - pip
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0,<3.0.0
    - toolbox_utils >=5.0.0,<6.0.0
    - tabulate
    - pandas
    - python-dateutil
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
