{% set name = "wdmtoolbox" %}
{% set version = "16.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<38]
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install --no-deps --only-binary ':all:' {{ name }}
  number: 0

requirements:
  host:
    - python
    - wheel
    - pip
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0,<3.0.0
    - {{ pin_compatible('numpy') }}
    - toolbox_utils >=5.0.0,<6.0.0
    - pandas
    - python-dateutil

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
