{% set name = "wdmtoolbox" %}
{% set version = "16.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wdmtoolbox-{{ version }}.tar.gz
  sha256: 08e3da076ae78ad86950a752c3699a9a38ffa442d6bfb2a5567def295cb6349d

build:
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - flang                      # [win]
    - {{ compiler('c') }}        # [unix]
    - clang                      # [win]
  host:
    - python
    - meson-python
    - wheel
    - numpy ==1.22.4  # [py<=310]
    - pip
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0,<3.0.0
    - toolbox_utils >=5.0.0,<6.0.0
    - {{ pin_compatible('numpy') }}
    - pandas
    - python-dateutil

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
