{% set name = "wdmtoolbox" %}
{% set version = "16.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wdmtoolbox-{{ version }}.tar.gz
  sha256: 794c67ea192179145c643290e729b72c9ce199e2082f1d4c98f0b8cee7746e62

build:
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler("m2w64_fortran") }}  # [win]
    - {{ compiler("m2w64_c") }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - meson-python
    - meson >=1.5.1
    - numpy >=2.0
    - python
    - setuptools-scm
  host:
    - meson-python
    - meson >=1.5.1
    - numpy >=2.0
    - pip
    - python
  run:
    - cltoolbox >=2.0.0
    - dateparser
    - filelock
    - numpy >=1.26
    - pandas
    - pint !=0.21.*
    - pint-pandas
    - pydantic
    - python
    - python-dateutil
    - scipy
    - tabulate


test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
