{% set name = "wdmtoolbox" %}
{% set version = "16.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wdmtoolbox-{{ version }}.tar.gz
  sha256: a766cbca02421f548cd6d0dd4dd8234114ce422c5ad7d2313e6d63f82c9c2f97

build:
  skip: true  # [py<38]
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - meson-python
    - numpy
  host:
    - python
    - meson-python
    - wheel
    - numpy
    - pip
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0,<3.0.0
    - {{ pin_compatible('numpy') }}
    - toolbox_utils >=5.0.0,<6.0.0
    - pandas
    - python-dateutil

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
