{% set name = "wdmtoolbox" %}
{% set version = "16.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/timcera/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9fbf12f1dff94ab6f16062a7e7bba517603b8d36943855796951fb0107716504

build:
  skip: true  # [py<38]
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m build --no-isolation --skip-dependency-check
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - meson
    - meson-python
    - numpy
  host:
    - python
    - python-build
    - meson-python
    - wheel
    - numpy ==1.22.4  # [py<=310]
    - pip
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0,<3.0.0
    - {{ pin_compatible('numpy') }}
    - toolbox_utils >=5.0.0,<6.0.0
    - pandas
    - python-dateutil

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
