{% set name = "wdmtoolbox" %}
{% set version = "16.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wdmtoolbox-{{ version }}.tar.gz
  sha256: 0da7f6f4522ba8e68baca37189e2786bd7e8f5b9a6ae02464daa872f3ecb5909

build:
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - meson-python
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - numpy
    - pip
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0,<3.0.0
    - toolbox_utils >=3.0.0,<4.0.0
    - pandas
    - python-dateutil
    - tabulate
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
