{% set name = "wdmtoolbox" %}
{% set version = "16.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wdmtoolbox-{{ version }}.tar.gz
  sha256: 0a7c699fc7fb9238876e18218023a61bf9cd141d614f54ab391f05c01755470d

build:
  skip: true  # [py<39]
  entry_points:
    - wdmtoolbox = wdmtoolbox.wdmtoolbox:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson-python
    - meson >=1.5.1
    - numpy >=2.0
    - python
    - setuptools-scm
  host:
    - meson-python
    - meson >=1.5.1
    - numpy >=2.0
    - pip
    - python
  run:
    - python
    - filelock
    - cltoolbox >=2.0.0
    - dateparser
    - numpy >=1.26
    - pandas
    - pint !=0.21.*
    - pint-pandas
    - pydantic
    - python-dateutil
    - scipy
    - tabulate

test:
  imports:
    - wdmtoolbox
  commands:
    - pip check
    - wdmtoolbox --help
  requires:
    - pip

about:
  summary: Read and write Watershed Data Management (WDM) files
  home: https://pypi.org/project/wdmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
